name: Deploy Static Site to Vercel

on:
  push:
    branches: [ "main" ]  # Запускать только при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Убедимся, что секреты доступны (DEBUG)
      run: |
        echo "Vercel Org ID: ${{ secrets.VERCEL_ORG_ID }}"
        echo "Vercel Project ID: ${{ secrets.VERCEL_PROJECT_ID }}"
        echo "Vercel Token: ${{ secrets.VERCEL_TOKEN }}"

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: .
